#!/bin/sh
set -e

python3 -m venv /opt/jarvis/venv || true
/opt/jarvis/venv/bin/pip install --upgrade pip "setuptools<70.0.0"
/opt/jarvis/venv/bin/pip install -r /opt/jarvis/frontend/requirements.txt
update-desktop-database || true

exit 0
